// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgyKRmAAFWGb-JxVA8gPAMu7V2QXEdOoE',
    appId: '1:651447355393:web:75771d5d3d17df29401800',
    messagingSenderId: '651447355393',
    projectId: 'taranaportel-hyd',
    authDomain: 'taranaportel-hyd.firebaseapp.com',
    storageBucket: 'taranaportel-hyd.appspot.com',
    measurementId: 'G-J5D2KLC4ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAKmRt7s0QR7GH9ix1-owbw4cXybWJSUg',
    appId: '1:651447355393:android:ff051e531ca1bfed401800',
    messagingSenderId: '651447355393',
    projectId: 'taranaportel-hyd',
    storageBucket: 'taranaportel-hyd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOekWNsaBx4qhxUR0uUS8KiuGaLHJJiBM',
    appId: '1:651447355393:ios:4c303e41309ec658401800',
    messagingSenderId: '651447355393',
    projectId: 'taranaportel-hyd',
    storageBucket: 'taranaportel-hyd.appspot.com',
    iosClientId: '651447355393-ustkt6s4u24sva2fkqc5019jik460e5b.apps.googleusercontent.com',
    iosBundleId: 'com.soulrelief.siohyd.soulrelief',
  );
}
